<?php
class FundChargeApply extends BaseModel {
	public function getTestData() {
		return 'application/testdata/FundChargeApply.php';
	}
	public function getDefaultMap() {
		return array (
				'orderId' => '00001111',
				'revAccName' => '默认账户',
				"rcvAccNum" => "",
				'rcvEmail' => '默认bank@mail.wa',
				'expireTime' => '1374804711﻿198',
				'breakUrl' => '',
				'cards' => array (
						'bankId' => '',
						'bankAccount' => '',
						'bankNumber' => '',
						'branchName' => '',
						'mcBankId' => '',
// 						'branchAddr' => '默认****',
						'bindDate' => ''
				),
				'chargeMemo' => '',
				'bankId' 	 => '',
				'rcvBankName' 	 => '',
				'mode' 		 => '',
			    'thPay' => array (
					'inputCharset' => 'UTF-8',
					'notifyUrl' =>'',
					'payType' =>'',
					'bankCode' =>'',
					'merchantCode' =>'',
					'orderNo' =>'',
					'orderAmount' =>'',
					'orderTime' =>'',
					'reqReferer' =>'',
					'customerIp' =>'',
			    ),
				'hbPay' => array (
					'inputCharset' => 'UTF-8',
					'transDomain' =>'',
					'hbUrl' =>'',
					'signature' =>'',
					'data' =>'',
				),
				'worthPay' => array (
					'service' =>'',
					'merchant_ID' =>'',
					'notify_url' =>'',
					'return_url' =>'',
					'charset' =>'',
					'title' =>'',
					'body' =>'',
					'order_no' =>'',
					'total_fee' =>'',
					'payment_type' =>'',
					'paymethod' =>'',
					'defaultbank' =>'',
					'seller_email' =>'',
					'isApp' =>'',
					'sign_type' =>'',
					'sign' =>'',
					'transDomain' =>'',
				),
				'spPay' => array (
					'inputCharset' => 'UTF-8',
					'transDomain' =>'', 
					'SIGN' =>'',
					'MERCNUM' =>'',
					'TRANDATA' =>'',
				),
				'ddbPay' => array (
					'inputCharset' => 'UTF-8',
					'transDomain' =>'',
					'merchantCode' =>'',
					'serviceType' =>'',
					'returnUrl' =>'',
					'notifyUrl' =>'',
					'interfaceVersion' =>'',
					'inputCharset' =>'',
					'signType' =>'',
					'orderNo' =>'',
					'orderTime' =>'',
					'orderAmount' =>'',
					'bankCode' =>'',
					'productName' =>'',
					'sign' =>'',
				),
				'wftPay' => array (
					'version' => '',
					'method' =>'',
					'partner' =>'',
					'banktype' =>'',
					'paymoney' =>'',
					'ordernumber' =>'',
					'callbackurl' =>'',
					'inputCharset' =>'',
					'isshow' =>'',
					'hrefbackurl' =>'', 
					'sign' =>'',
				),
				'dinPay' => array (
					'inputCharset' => 'UTF-8',
					'transDomain' =>'',
					'merchantCode' =>'',
					'serviceType' =>'',
					'returnUrl' =>'',
					'notifyUrl' =>'',
					'interfaceVersion' =>'',
					'inputCharset' =>'',
					'signType' =>'',
					'orderNo' =>'',
					'orderTime' =>'',
					'orderAmount' =>'',
					'bankCode' =>'',
					'productName' =>'',
					'sign' =>'',
				),
				'huayinPay' => array (
					'inputCharset' => 'UTF-8',
					'transDomain' =>'',
					'merchantCode' =>'',
					'serviceType' =>'',
					'returnUrl' =>'',
					'notifyUrl' =>'',
					'interfaceVersion' =>'',
					'inputCharset' =>'',
					'signType' =>'',
					'orderNo' =>'',
					'orderTime' =>'',
					'orderAmount' =>'',
					'bankCode' =>'',
					'productName' =>'',
					'sign' =>'',
				),
				'yinbangPay' => array (
				'transDomain' =>'',
				'merId' =>'',
				'version' =>'',
				'encParam' =>'',
				'sign' =>'',
				),
				'jinyangPay' => array (
				'transDomain' =>'',
				'merId' =>'',
				'payType' =>'',
				'paymoney' =>'',
				'orderno' =>'',
				'asynURL' =>'', 
				'version' =>'',
				'signType' =>'',
				'isShow' =>'',
				'sign' =>'',
				),
		);
	}
}