REM INSERTING into GAME_AWARD_GROUP
SET DEFINE OFF;
Insert into GAME_AWARD_GROUP (ID,LOTTERYID,AWARD_NAME,DIRECT_RET,THREEONE_RET,STATUS,SYS_AWARD_GROUP,CREATE_TIME,UPDATE_TIME,PARAMS,AWARD_RET_STATUS,SUPER_RET,SUPER_PAIR_STATUS) values (201,88102,'混合奖金组',200,0,1,1,sysdate,sysdate,null,1,0,1);
