REM INSERTING into GAME_SERIES
SET DEFINE OFF;
Insert into GAME_SERIES (ID,LOTTERY_TYPE_CODE,LOTTERY_TYPE_NAME,LOTTERY_SERIES_CODE,LOTTERY_SERIES_NAME,LOTTERYID,LOTTERY_NAME,STATUS,CREATE_TIME,UPDATE_TIME,MINI_LOTTERY_PROFIT,LOTTERY_HELP_DES,MAX_COUNT_ISSUE,LOTTERY_IS_LOCK,CHANGE_STATUS,EMAIL,VIEW_ORDER,OPERATE_ORDER) values (27,5,'游艺型',8,'电子游艺',88102,'FHX',1,sysdate,sysdate,0.04,'全天',0,0,null,null,null,null);
