package com.winterframework.firefrog.game.enums;

/**
 * 六合彩投注類型
 * @author Pogi.Lin
 */
public enum GameLHCBetType {
	/**直选一码:zhixuanema*/
	ZHIXUANEMA("zhixuanema"),
	/**特肖副肖:UNYEAR*/
	SAISHAI_UNYEAR("UNYEAR"),
	/**特肖主肖:ONYEAR*/
	SAISHAI_ONYEAR("ONYEAR"),
	/**两面:TWOFACE*/
	LIANGMIAN("TWOFACE"),
	/**色波紅:RED*/
	SAPO_RED("RED"),
	/**色波藍:BLUE*/
	SAPO_BLUE("BLUE"),
	/**色波綠:GREEN*/
	SAPO_GREEN("GREEN"),
	/**半波(紅大):REDBIG*/
	BANBO_REDBIG("REDBIG"),
	/**半波(紅小):REDSMALL*/
	BANBO_REDSMALL("REDSMALL"),
	/**半波(紅單):REDODD*/
	BANBO_REDODD("REDODD"),
	/**半波(紅雙):REDEVEN*/
	BANBO_REDEVEN("REDEVEN"),
	/**半波(藍大):BLUEBIG*/
	BANBO_BLUEBIG("BLUEBIG"),
	/**半波(藍小):BLUESMALL*/
	BANBO_BLUESMALL("BLUESMALL"),
	/**半波(藍單):BLUEODD*/
	BANBO_BLUEODD("BLUEODD"),
	/**半波(藍雙):BLUEEVEN*/
	BANBO_BLUEEVEN("BLUEEVEN"),
	/**半波(綠大):GREENBIG*/
	BANBO_GREENBIG("GREENBIG"),
	/**半波(綠小):GREENSMALL*/
	BANBO_GREENSMALL("GREENSMALL"),
	/**半波(綠單):GREENODD*/
	BANBO_GREENODD("GREENODD"),
	/**半波(綠雙):GREENEVEN*/
	BANBO_GREENEVEN("GREENEVEN"),
	/**四不中:NOTIN4*/
	NOTIN4("NOTIN4"),
	/**五不中:NOTIN5*/
	NOTIN5("NOTIN5"),
	/**六不中:NOTIN6*/
	NOTIN6("NOTIN6"),
	/**七不中:NOTIN7*/
	NOTIN7("NOTIN7"),
	/**八不中:NOTIN8*/
	NOTIN8("NOTIN8"),
	/**二連肖主肖(中):ONCONTINUEIN2*/
	ONCONTINUEIN2("ONCONTINUEIN2"),
	/**三連肖主肖(中):ONCONTINUEIN3*/
	ONCONTINUEIN3("ONCONTINUEIN3"),
	/**四連肖主肖(中):ONCONTINUEIN4*/
	ONCONTINUEIN4("ONCONTINUEIN4"),
	/**五連肖主肖(中):ONCONTINUEIN5*/
	ONCONTINUEIN5("ONCONTINUEIN5"),
	/**二連肖副肖(中):UNCONTINUEIN2*/
	UNCONTINUEIN2("UNCONTINUEIN2"),
	/**三連肖副肖(中):UNCONTINUEIN3*/
	UNCONTINUEIN3("UNCONTINUEIN3"),
	/**四連肖副肖(中):UNCONTINUEIN4*/
	UNCONTINUEIN4("UNCONTINUEIN4"),
	/**五連肖副肖(中):UNCONTINUEIN5*/
	UNCONTINUEIN5("UNCONTINUEIN5"),
	/**二連肖主肖(不中):ONCONTINUENOTIN2*/
	ONCONTINUENOTIN2("ONCONTINUENOTIN2"),
	/**三連肖主肖(不中):ONCONTINUENOTIN3*/
	ONCONTINUENOTIN3("ONCONTINUENOTIN3"),
	/**四連肖主肖(不中):ONCONTINUENOTIN4*/
	ONCONTINUENOTIN4("ONCONTINUENOTIN4"),
	/**五連肖主肖(不中):ONCONTINUENOTIN5*/
	ONCONTINUENOTIN5("ONCONTINUENOTIN5"),
	/**二連肖副肖(不中):UNCONTINUENOTIN2*/
	UNCONTINUENOTIN2("UNCONTINUENOTIN2"),
	/**三連肖副肖(不中):UNCONTINUENOTIN3*/
	UNCONTINUENOTIN3("UNCONTINUENOTIN3"),
	/**四連肖副肖(不中):UNCONTINUENOTIN4*/
	UNCONTINUENOTIN4("UNCONTINUENOTIN4"),
	/**五連肖副肖(不中):UNCONTINUENOTIN5*/
	UNCONTINUENOTIN5("UNCONTINUENOTIN5"),
	/**連碼三全中:CONTINUECODE333*/
	CONTINUECODE333("CONTINUECODE333"),
	/**連碼三中二(中二):CONTINUECODE322*/
	CONTINUECODE322("CONTINUECODE322"),
	/**連碼三中二(中三):CONTINUECODE323*/
	CONTINUECODE323("CONTINUECODE323"),
	/**連碼二全中:CONTINUECODE2Z*/
	CONTINUECODE2Z("CONTINUECODE2Z"),
	/**連碼二中特(中二):CONTINUECODE22Z*/
	CONTINUECODE22Z("CONTINUECODE22Z"),
	/**連碼二中特(中特):CONTINUECODE22T*/
	CONTINUECODE22T("CONTINUECODE22T"),
	/**連碼特串:CONTINUECODE2T*/
	CONTINUECODE2T("CONTINUECODE2T")
	;
	
	private String type;
	private GameLHCBetType(String type){
		this.type=type;
	}
	
	public String getType() {
		return type;
	} 
}
