package com.winterframework.firefrog.session.interceptor;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.servlet.ModelAndView;

import com.winterframework.firefrog.session.interceptor.vo.AclUserStruc;
import com.winterframework.modules.spring.exetend.PropertyConfig;
import com.winterframework.modules.web.util.JsonMapper;
import com.winterframework.modules.web.util.RequestContext;

/**
 * 
* @ClassName: AclInterceptor 
* @Description: 后台页面请求拦截器，判断session是否有效和是否有权限 
* @author Page 
* @date 2014-1-22 下午2:25:16 
*
 */
public class AdminUserAclInterceptor extends AbstractAclInterceptor {
	private static final Logger logger = LoggerFactory.getLogger(AdminUserAclInterceptor.class);
	@PropertyConfig(value = "url.admin.login")
	protected String redirectAddr;

	@Override
	public boolean preHandle(HttpServletRequest request, HttpServletResponse response, Object handler) throws Exception {
		//判断用户session是否有效
		if ( RequestContext.get().session()==null || RequestContext.get().session().getAttribute("info")==null) {
			response.sendRedirect(redirectAddr);
			return false;
		} 
		//判断用户权限
		logger.debug("check user has permission.");
		final AclUserStruc map = JsonMapper.nonAlwaysMapper().fromMapToObject(
				RequestContext.get().session().getAttribute("info"), AclUserStruc.class);
		RequestContext.setIUer(map);
		request.setAttribute("userName",map.getAccount());
		logger.debug((map==null) ?null :map.getAcls().toString());
		if (map != null) {
			request.setAttribute("aclList", map.getAcls());
			request.setAttribute("userName",RequestContext.getCurrUser().getUserName());
		}
		return true;
	}
	/**
	 * This implementation is empty.
	 */
	@Override
	public void postHandle(
			HttpServletRequest request, HttpServletResponse response, Object handler, ModelAndView modelAndView)
			throws Exception {
	}
	public String getRedirectAddr() {
		return redirectAddr;
	}
	public static void main(String[] a){
		String abc="{\"id\":1,\"passwd\":\"e10adc3949ba59abbe56e057f20f883e\",\"account\":\"cancus\",\"bindPasswd\":\"SS0000609000033709EF051E0FD117D69BBE4C4134948039468A9D6201A1F989982A53D1E740C5BB6A173EEAD45AE64CA534B4FC4F1A2FE5593AF29C1686D5E1E10FD2877B2AD8F3208FDAED426EF5BE1212DC9ADEF8143C240447C7B4F691DB60E85EAEFBB7B12890E85EAEFBB7B12890E85EAEFBB7B12890E85EAEFBB7B12890E85EAEFBB7B12890E85EAEFBB7B1289==\",\"dep\":\"PMD\",\"cellphone\":\"100\",\"telephone\":\"200\",\"email\":null,\"status\":0,\"groupId\":66,\"groupName\":\"\",\"createder\":null,\"modifieder\":null,\"gmtCreated\":null,\"gmtModified\":null,\"acls\":[\"FUND_MANUAL_PROCEDURE_CREATE\",\"GLOBAL_SENSITIVEWORDSETTING\",\"GLOBAL_IPSWITCH\",\"GLOBAL_IPILLEGALITY\",\"GLOBAL_IPLEGAL\",\"HELP\",\"HELP_CENTER\",\"HELP_MANAGER\",\"HELP_NEWHELP\",\"HELP_CATEGORY\",\"HELP_HELPCONFIG\",\"NOTICE_CENTER\",\"NOTICE_SITEMSG\",\"NOTICE_SENDSITEMSG\",\"NOTICE_SYSMSGMANAGER\",\"NOTICE_USERMSGMANAGER\",\"NOTICE_EMAIL\",\"NOTICE_EMAILCONFIG\",\"NOTICE_TASK\",\"NOTICE_TASKMANAGER\",\"ACL\",\"ACL_CENTER\",\"ACL_ACLGROUPMANAGER\",\"ACL_CREATEACLGROUP\",\"ACL_USERMANAGER\",\"ACL_ADDUSER\",\"ACL_OPERATELOG\",\"ACL_MODFIYPASSWORD\",\"GLOBAL_REGEISTLOGINSETTING\",\"MARKET\",\"MARKET_ADVERT\",\"MARKET_ADVERTMANAGERPUB\",\"MARKET_ADDADVERT\",\"MARKET_ADVERTMANAGERAUDIT\",\"MARKET_ADSPACEMANAGER\",\"MARKET_ADDADSPACE\",\"MARKET_MODIFYADSPACE\",\"MARKET_UNBINGADSPACE\",\"MARKET_NOTICE\",\"MARKET_NOTICEANAGERPUB\",\"MARKET_NOTICEANAGERAUDIT\",\"MARKET_ADDNOTICE\",\"MARKET_NORMALNOTICE\",\"MARKET_URGENCYNOTICE\",\"MARKET_SUBJECT\",\"MARKET_SUBJECTMANAGER\",\"MARKET_MODIFYSUBJECT\",\"MARKET_ADDSUBJECT\",\"GLOBAL\",\"GLOBAL_GLOBALMANAGER\",\"GAME\",\"GAME_LOTMGR\",\"GAME_LOTMGR_LOTLIST\",\"GAME_LOTMGR_LOTLIST_RULE\",\"GAME_LOTMGR_LOTLIST_RULE_ADD\",\"GAME_LOTMGR_LOTLIST_RULE_VIEW\",\"GAME_LOTMGR_LOTLIST_RULE_EDIT\",\"GAME_LOTMGR_LOTLIST_RULE_DEL\",\"GAME_LOTMGR_LOTLIST_RULE_AUDIT\",\"GAME_LOTMGR_LOTLIST_AWARDGROUP\",\"GAME_LOTMGR_LOTLIST_AWARDGROUP_ADD\",\"GAME_LOTMGR_LOTLIST_AWARDGROUP_VIEW\",\"GAME_LOTMGR_LOTLIST_AWARDGROUP_EDIT\",\"GAME_LOTMGR_LOTLIST_AWARDGROUP_DEL\",\"GAME_LOTMGR_LOTLIST_AWARDGROUP_AUDIT\",\"GAME_LOTMGR_LOTLIST_AWARDGROUP_PUBLISH\",\"GAME_LOTMGR_LOTLIST_BETLIMIT\",\"GAME_LOTMGR_LOTLIST_BETLIMIT_EDIT\",\"GAME_LOTMGR_LOTLIST_BETLIMIT_AUDIT\",\"GAME_LOTMGR_LOTLIST_BETLIMIT_EDIT2\",\"GAME_LOTMGR_LOTLIST_BETLIMIT_PUBLISH\",\"GAME_LOTMGR_LOTLIST_HELP\",\"GAME_LOTMGR_LOTLIST_HELP_EDIT\",\"GAME_LOTMGR_LOTLIST_HELP_AUDIT\",\"GAME_LOTMGR_LOTLIST_HELP_EDIT2\",\"GAME_LOTMGR_LOTLIST_HELP_PUBLISH\",\"GAME_LOTMGR_LOTLIST_SALESTATUS\",\"GAME_LOTMGR_LOTLIST_SALESTATUS_EDIT\",\"GAME_LOTMGR_LOTLIST_SALESTATUS_AUDIT\",\"GAME_LOTMGR_LOTLIST_SALESTATUS_EDIT2\",\"GAME_LOTMGR_LOTLIST_SALESTATUS_PUBLISH\",\"GAME_LOTMGR_LOTLIST_CONFIG\",\"GAME_LOTMGR_LOTLIST_CONFIG_BET\",\"GAME_LOTMGR_LOTLIST_CONFIG_PACKAGE\",\"GAME_LOTMGR_LOTLIST_CONFIG_ISSUE\",\"GAME_LOTMGR_LOTLIST_CONFIG_EDIT\",\"GAME_LOTMGR_LOTLIST_CONFIG_AUDIT\",\"GAME_LOTMGR_LOTLIST_CONFIG_EDIT2\",\"GAME_LOTMGR_LOTLIST_CONFIG_PUBLISH\",\"GAME_ISSUEMGR\",\"GAME_ISSUEMGR_MONITOR\",\"GAME_ISSUEMGR_MONITOR_DETAIL\",\"GAME_ISSUEMGR_MONITOR_SETACTUALNUM\",\"GAME_ISSUEMGR_MONITOR_PAUSE\",\"GAME_ISSUEMGR_MONITOR_CONTINUE\",\"GAME_ISSUEMGR_MONITOR_REVOKEISSUE\",\"GAME_ISSUEMGR_MONITOR_REVOKEPLAN\",\"GAME_ISSUEMGR_MONITOR_SETNUM\",\"GAME_ISSUEMGR_MONITOR_AUDITALL\",\"GAME_ISSUEMGR_MONITOR_AUDIT\",\"GAME_ISSUEMGR_WARNLOG\",\"GAME_OPMGR\",\"GAME_OPMGR_ORDERLIST\",\"GAME_OPMGR_ORDERLIST_DETAIL\",\"GAME_OPMGR_ORDERLIST_DETAIL_REVOKE\",\"GAME_OPMGR_PLANLIST\",\"GAME_OPMGR_PLANLIST_DETAIL\",\"GAME_OPMGR_PLANLIST_DETAIL_REVOKE\",\"GAME_OPMGR_PLANLIST_DETAIL_STOP\",\"GAME_OPMGR_WARNLIST\",\"GAME_OPMGR_WARNLIST_WARN\",\"GAME_OPMGR_WARNLIST_SPITE\",\"GAME_OPMGR_WARNLIST_SPITE_DETAIL\",\"GAME_REPORT\",\"GAME_REPORT_WINS\",\"GAME_REPORT_WINS_DETAIL\",\"FUND\",\"FUND_RECHARGE\",\"FUND_RECHARGE_EXCEPTION\",\"FUND_RECHARGE_EXCEPTION_ALL\",\"FUND_RECHARGE_EXCEPTION_UNTREATED\",\"FUND_RECHARGE_EXCEPTION_UNTREATED_ADDCOINS\",\"FUND_RECHARGE_EXCEPTION_UNTREATED_RETURNMONEY\",\"FUND_RECHARGE_EXCEPTION_UNTREATED_UPDATEINFO\",\"FUND_RECHARGE_EXCEPTION_UNTREATED_CONFISCATE\",\"FUND_RECHARGE_EXCEPTION_REVIEW\",\"FUND_RECHARGE_EXCEPTION_REVIEW_ADDCOINS\",\"FUND_RECHARGE_EXCEPTION_REVIEW_RETURNMONEY\",\"FUND_RECHARGE_EXCEPTION_REVIEW_CONFISCATE\",\"FUND_RECHARGE_EXCEPTION_HANDLING\",\"FUND_RECHARGE_EXCEPTION_SOLVED\",\"FUND_RECHARGE_EXCEPTION_SOLVED_DOWNLOAD\",\"FUND_RECHARGE_EXCEPTION_DISPLAYCOLS\",\"FUND_RECHARGE_CONFIG\",\"FUND_RECHARGE_CONFIG_UPTO\",\"FUND_RECHARGE_CONFIG_UPTO_SUBMIT\",\"FUND_RECHARGE_CONFIG_RETURN\",\"FUND_RECHARGE_CONFIG_RETURN_SUBMIT\",\"FUND_WITHDRAW\",\"FUND_WITHDRAW_RISK\",\"FUND_WITHDRAW_RISK_ALL\",\"FUND_WITHDRAW_RISK_UNTREATED\",\"FUND_WITHDRAW_RISK_UNTREATED_PASS\",\"FUND_WITHDRAW_RISK_UNTREATED_REFUSE\",\"FUND_WITHDRAW_RISK_UNTREATED_REVIEW\",\"FUND_WITHDRAW_RISK_REVIEW\",\"FUND_WITHDRAW_RISK_REVIEW_PASS\",\"FUND_WITHDRAW_RISK_REVIEW_REFUSE\",\"FUND_WITHDRAW_RISK_HANDLING\",\"FUND_WITHDRAW_RISK_RESOLVED\",\"FUND_WITHDRAW_RISK_DOWNLOAD\",\"FUND_WITHDRAW_CONFIG\",\"FUND_WITHDRAW_CONFIG_UPDOWN\",\"FUND_WITHDRAW_CONFIG_UPDOWN_SUBMIT\",\"FUND_WITHDRAW_CONFIG_DISABLED\",\"FUND_WITHDRAW_CONFIG_DISABLED_SUBMIT\",\"FUND_WITHDRAW_CONFIG\",\"FUND_WITHDRAW_CONFIG_SUBMIT\",\"FUND_MANUAL\",\"FUND_MANUAL_PROCEDURE\",\"FUND_MANUAL_PROCEDURE_ALL\",\"FUND_MANUAL_PROCEDURE_UNTREATED\",\"FUND_MANUAL_PROCEDURE_UNTREATED_PASS\",\"FUND_MANUAL_PROCEDURE_UNTREATED_REFUSE\",\"FUND_MANUAL_PROCEDURE_HANDLING\",\"FUND_MANUAL_PROCEDURE_RESOLVED\",\"FUND_MANUAL_PROCEDURE_DOWNLOAD\",\"FUND_BANKCARD\",\"FUND_BANKCARD_BANKMANAGE\",\"FUND_BANKCARD_BANKMANAGE_RECHARGE\",\"FUND_BANKCARD_BANKMANAGE_RECHARGE_CREATE\",\"FUND_BANKCARD_BANKMANAGE_RECHARGE_CHANGESTAUS\",\"FUND_BANKCARD_BANKMANAGE_RECHARGE_EDIT\",\"FUND_BANKCARD_BANKMANAGE_WITHDRAW\",\"FUND_BANKCARD_BANKMANAGE_WITHDRAW_CREATE\",\"FUND_BANKCARD_BANKMANAGE_WITHDRAW_CHANGESTATUS\",\"FUND_BANKCARD_BANKMANAGE_WITHDRAW_EDIT\",\"FUND_BANKCARD_BANKMANAGE_BINDCARDCOUNT\",\"FUND_BANKCARD_BANKMANAGE_BINDCARDCOUNT_SUBMIT\",\"FUND_BANKCARD_BINDMANAGE\",\"FUND_BANKCARD_BINDMANAGE_CHANGESTATUS\",\"FUND_BANKCARD_BINDMANAGE_HISTORY\",\"FUND_BANKCARD_BLACKLIST\",\"FUND_BANKCARD_BLACKLIST_CREATE\",\"FUND_TRANSFER\",\"FUND_TRANSFER_LIST\",\"FUND_TRANSFER_CONFIG\",\"FUND_TRANSFER_CONFIG_SUBMIT\",\"USER\",\"USER_MANAGE\",\"USER_MANAGE_LIST\",\"USER_MANAGE_LIST_SEARCH\",\"USER_MANAGE_LIST_CHANGEVIP\",\"USER_MANAGE_LIST_INFO\",\"USER_MANAGE_LIST_INFO_USERINFO\",\"USER_MANAGE_LIST_INFO_BINDCARD\",\"USER_MANAGE_LIST_INFO_PRIZE\",\"USER_MANAGE_LIST_FREEZE\",\"USER_MANAGE_LIST_ACCOUNTDETAIL\",\"USER_MANAGE_LIST_CATHECTICHISTORY\",\"USER_MANAGE_TOPAGENT\",\"USER_MANAGE_TOPAGENT_LIST\",\"USER_MANAGE_TOPAGENT_LIST_CHANGEVIP\",\"USER_MANAGE_TOPAGENT_LIST_INFO\",\"USER_MANAGE_TOPAGENT_LIST_INFO_USERINFO\",\"USER_MANAGE_TOPAGENT_LIST_INFO_BINDCARD\",\"USER_MANAGE_TOPAGENT_LIST_INFO_PRIZE\",\"USER_MANAGE_TOPAGENT_LIST_FREZE\",\"USER_MANAGE_TOPAGENT_LIST_ACCOUNTDETAIL\",\"USER_MANAGE_TOPAGENT_LIST_CATHECTICHISTORY\",\"USER_MANAGE_TOPAGENT_LIST_CREATEUSERCNT\",\"USER_MANAGE_TOPAGENT_CREATETOPAGENT\",\"USER_EXCEPTION\",\"USER_EXCEPTION_FREEZEUSER\",\"USER_EXCEPTION_FREEZEUSER_LIST\",\"USER_EXCEPTION_FREEZEUSER_LIST_SEARCH\",\"USER_EXCEPTION_FREEZEUSER_LIST_UNFREEZE\",\"USER_EXCEPTION_FREEZEUSER_HISTORY\",\"USER_EXCEPTION_FREEZYldo2J{i{XYC2EUSER_HISTORY_SEARCH\",\"USER_EXCEPTION_APPEAL\",\"USER_EXCEPTION_APPEAL_SEARCH\",\"USER_EXCEPTION_APPEAL_INFO\",\"USER_EXCEPTION_APPEAL_INFO_USERINFO\",\"USER_EXCEPTION_APPEAL_INFO_BINDCARD\",\"USER_EXCEPTION_APPEAL_INFO_PRIZE\",\"USER_EXCEPTION_APPEAL_VERIFY\",\"FUND_RECHARGE_REMARK_MANAGER_UNBIND\",\"FUND_RECHARGE_REMARK\",\"FUND_RECHARGE_REMARK_MANAGER\",\"FUND_RECHARGE_REMARK_MANAGER_UNLOCK\",\"FUND_RECHARGE_REMARK_MANAGER_DOWNLOAD\",\"FUND_RECHARGE_REMARK_RECYCLE\",\"FUND_RECHARGE_REMARK_RECYCLE_OPT\",\"FUND_RECHARGE_REMARK_RECYCLE_DOWNLOAD\",\"FUND_RECHARGE_REMARK_SETTING\",\"FUND_RECHARGE_REMARK_SETTING_SAVE\",\"FUND_RECHARGE_REMARK_SETTING_IMPORT\"]}";
		// abc="{\"id\":1,\"passwd\":\"e10adc3949ba59abbe56e057f20f883e\"}";
		 AclUserStruc st= JsonMapper.nonDefaultMapper().fromJson(abc, AclUserStruc.class);
		AclUserStruc map = JsonMapper.nonDefaultMapper().fromMapToObject(st, AclUserStruc.class);
		System.out.println(1);
		
	}
	
}
