  
--insert into GAME_SERIES
insert into GAME_SERIES (ID, LOTTERY_TYPE_CODE, LOTTERY_TYPE_NAME, LOTTERY_SERIES_CODE, LOTTERY_SERIES_NAME, LOTTERYID, LOTTERY_NAME, STATUS, CREATE_TIME, UPDATE_TIME, MINI_LOTTERY_PROFIT, LOTTERY_HELP_DES, MAX_COUNT_ISSUE,LOTTERY_IS_LOCK,CHANGE_STATUS)
values ((select max(id)+1 from GAME_SERIES), 1, '数字型', 1, '时时彩系', 99113, '超级2000秒秒彩（APP版）', 1, sysdate, sysdate, 0.04, '全天：120期  123【白天】10:00-22:00，15分钟/期 【夜间】22:00-01:55，8分钟/期 ', 0,255,11111111);
  
--insert into GAME_BETTYPE_STATUS  
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,10,10,1,sysdate,sysdate,20000000,'47_10_10',110,'housan_2000','zhixuan','fushi','超级2000_后三','直选','复式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,10,11,1,sysdate,sysdate,20000000,'47_10_11',110,'housan_2000','zhixuan','danshi','超级2000_后三','直选','单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,10,33,1,sysdate,sysdate,20000000,'47_10_33',110,'housan_2000','zhixuan','hezhi','超级2000_后三','直选','直选和值');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,10,34,1,sysdate,sysdate,20000000,'47_10_34',110,'housan_2000','zhixuan','kuadu','超级2000_后三','直选','跨度');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,11,33,1,sysdate,sysdate,6666700,'47_11_33',110,'housan_2000','zuxuan','hezhi','超级2000_后三','组选','组选和值');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,11,35,1,sysdate,sysdate,6660670,'47_11_35',110,'housan_2000','zuxuan','zusan','超级2000_后三','组选','组三');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,11,36,1,sysdate,sysdate,3333030,'47_11_36',110,'housan_2000','zuxuan','zuliu','超级2000_后三','组选','组六');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,11,37,1,sysdate,sysdate,6666700,'47_11_37',110,'housan_2000','zuxuan','hunhezuxuan','超级2000_后三','组选','混合组选');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,11,39,1,sysdate,sysdate,6666700,'47_11_39',110,'housan_2000','zuxuan','baodan','超级2000_后三','组选','组选包胆');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,11,62,1,sysdate,sysdate,6660670,'47_11_62',110,'housan_2000','zuxuan','zusandanshi','超级2000_后三','组选','组三单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,11,63,1,sysdate,sysdate,3330330,'47_11_63',110,'housan_2000','zuxuan','zuliudanshi','超级2000_后三','组选','组六单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,12,40,1,sysdate,sysdate,73000,'47_12_40',110,'housan_2000','budingwei','yimabudingwei','超级2000_后三','不定位','一码不定位');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,47,12,41,1,sysdate,sysdate,370400,'47_12_41',110,'housan_2000','budingwei','ermabudingwei','超级2000_后三','不定位','二码不定位');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,10,10,1,sysdate,sysdate,2000000,'48_10_10',130,'houer_2000','zhixuan','fushi','超级2000_后二','直选','直选复式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,10,11,1,sysdate,sysdate,2000000,'48_10_11',130,'houer_2000','zhixuan','danshi','超级2000_后二','直选','直选单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,10,33,1,sysdate,sysdate,2000000,'48_10_33',130,'houer_2000','zhixuan','hezhi','超级2000_后二','直选','直选和值');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,10,34,1,sysdate,sysdate,2000000,'48_10_34',130,'houer_2000','zhixuan','kuadu','超级2000_后二','直选','跨度');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,11,10,1,sysdate,sysdate,1000000,'48_11_10',130,'houer_2000','zuxuan','fushi','超级2000_后二','组选','组选复式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,11,11,1,sysdate,sysdate,1000000,'48_11_11',130,'houer_2000','zuxuan','danshi','超级2000_后二','组选','组选单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,11,33,1,sysdate,sysdate,1000000,'48_11_33',130,'houer_2000','zuxuan','hezhi','超级2000_后二','组选','组选和值');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,48,11,39,1,sysdate,sysdate,1000000,'48_11_39',140,'houer_2000','zuxuan','baodan','超级2000_后二','组选','组选包胆');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,50,14,10,1,sysdate,sysdate,200000,'50_14_10',150,'yixing_2000','dingweidan','fushi','超级2000_一星','定位胆','复式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,10,10,1,sysdate,sysdate,200000000,'51_10_10',20,'sixing_2000','zhixuan','fushi','超级2000_四星','直选','复式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,10,11,1,sysdate,sysdate,200000000,'51_10_11',20,'sixing_2000','zhixuan','danshi','超级2000_四星','直选','单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,11,50,1,sysdate,sysdate,16666600,'51_11_50',20,'sixing_2000','zuxuan','zuxuan12','超级2000_四星','组选','组选12');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,11,52,1,sysdate,sysdate,50000000,'51_11_52',20,'sixing_2000','zuxuan','zuxuan4','超级2000_四星','组选','组选4');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,12,41,1,sysdate,sysdate,205300,'51_12_41',20,'sixing_2000','budingwei','ermabudingwei','超级2000_四星','不定位','二码不定位');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,11,49,1,sysdate,sysdate,8333300,'51_11_49',20,'sixing_2000','zuxuan','zuxuan24','超级2000_四星','组选','组选24');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,11,51,1,sysdate,sysdate,33333300,'51_11_51',20,'sixing_2000','zuxuan','zuxuan6','超级2000_四星','组选','组选6');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,51,12,40,1,sysdate,sysdate,58100,'51_12_40',20,'sixing_2000','budingwei','yimabudingwei','超级2000_四星','不定位','一码不定位');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,10,11,1,sysdate,sysdate,20000000,'52_10_11',35,'zhongsan_2000','zhixuan','danshi','超级2000_中三','直选','单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,10,34,1,sysdate,sysdate,20000000,'52_10_34',35,'zhongsan_2000','zhixuan','kuadu','超级2000_中三','直选','跨度');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,11,35,1,sysdate,sysdate,6666600,'52_11_35',35,'zhongsan_2000','zuxuan','zusan','超级2000_中三','组选','组三');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,11,37,1,sysdate,sysdate,6666600,'52_11_37',35,'zhongsan_2000','zuxuan','hunhezuxuan','超级2000_中三','组选','混合组选');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,11,62,1,sysdate,sysdate,6666600,'52_11_62',35,'zhongsan_2000','zuxuan','zusandanshi','超级2000_中三','组选','组三单式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,12,40,1,sysdate,sysdate,73800,'52_12_40',35,'zhongsan_2000','budingwei','yimabudingwei','超级2000_中三','不定位','一码不定位');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,12,41,1,sysdate,sysdate,370300,'52_12_41',35,'zhongsan_2000','budingwei','ermabudingwei','超级2000_中三','不定位','二码不定位');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,10,10,1,sysdate,sysdate,20000000,'52_10_10',35,'zhongsan_2000','zhixuan','fushi','超级2000_中三','直选','复式');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,10,33,1,sysdate,sysdate,20000000,'52_10_33',35,'zhongsan_2000','zhixuan','hezhi','超级2000_中三','直选','直选和值');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,11,36,1,sysdate,sysdate,3333300,'52_11_36',35,'zhongsan_2000','zuxuan','zuliu','超级2000_中三','组选','组六');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,11,33,1,sysdate,sysdate,6666600,'52_11_33',35,'zhongsan_2000','zuxuan','hezhi','超级2000_中三','组选','组选和值');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,11,39,1,sysdate,sysdate,6666600,'52_11_39',35,'zhongsan_2000','zuxuan','baodan','超级2000_中三','组选','组选包胆');
Insert into GAME_BETTYPE_STATUS (ID,LOTTERYID,GAME_GROUP_CODE,GAME_SET_CODE,BET_METHOD_CODE,STATUS,CREATE_TIME,UPDATE_TIME,THEORY_BONUS,BET_TYPE_CODE,ORDERBY,GROUP_CODE_NAME,SET_CODE_NAME,METHOD_CODE_NAME,GROUP_CODE_TITLE,SET_CODE_TITLE,METHOD_CODE_TITLE) values (seq_game_bettype_status_id.nextval,99113,52,11,63,1,sysdate,sysdate,3333300,'52_11_63',35,'zhongsan_2000','zuxuan','zuliudanshi','超级2000_中三','组选','组六单式');



 --insert game_award_group  
Insert into GAME_AWARD_GROUP (ID,LOTTERYID,AWARD_NAME,DIRECT_RET,THREEONE_RET,STATUS,SYS_AWARD_GROUP,CREATE_TIME,UPDATE_TIME,PARAMS,AWARD_RET_STATUS,SUPER_RET,SUPER_PAIR_STATUS,LHC_YEAR,LHC_COLOR) values (
(select max(id)+1 from GAME_AWARD_GROUP),99113,'2000奖金组',0,0,1,1,sysdate,sysdate,null,0,100,1,0,0);
 
 --insert GAME_AWARD_USER_GROUP  
Insert into GAME_AWARD_USER_GROUP   
(select seq_game_award_user_group_id.nextval,99113,0,0,sysdate,sysdate,a.userid,1,1,1,(select (id) from GAME_AWARD_GROUP where lotteryid = '99113'),0,0,0 from 
(select userid from GAME_AWARD_USER_GROUP group by userid) a);

--insert GameAward 2000  mmc2000 award=1bet*peilv+1bet
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_10_10',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_10_10',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_10_11',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_10_11',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_10_33',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_10_33',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_10_34',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_10_34',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_33',0,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_33',0,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_33_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_33',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_33_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_33',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_35',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_35',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_36',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_36',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_37',0,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_37',0,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_37_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_37',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_37_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_37',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_39',0,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_39',0,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_39_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_39',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_39_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_39',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_62',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_11_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_11_63',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_12_40',73000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_12_40',36000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'47_12_41',360000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'47_12_41',180000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_10_10',2000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_10_10',1000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_10_11',2000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_10_11',1000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_10_33',2000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_10_33',1000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_10_34',2000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_10_34',1000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_11_10',1000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_11_10',500000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_11_11',1000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_11_11',500000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_11_33',1000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_11_33',500000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'48_11_39',1000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'48_11_39',500000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'50_14_10',200000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'50_14_10',100000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_10_10',200000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_10_10',100000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_10_11',200000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_10_11',100000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_11_49',8330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_11_49',4160000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_11_50',16660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_11_50',8330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_11_51',33330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_11_51',16660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_11_52',50000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_11_52',25000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_12_40',58000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_12_40',29000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'51_12_41',200000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'51_12_41',100000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_10_10',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_10_10',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_10_11',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_10_11',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_10_33',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_10_33',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_10_34',20000000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_10_34',10000000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_33',0,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_33',0,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_33_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_33',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_33_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_33',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_35',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_35',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_36',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_36',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_37',0,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_37',0,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_37_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_37',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_37_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_37',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_39',0,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_39',0,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_39_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_39',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_39_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_39',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_62',6660000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_62',3330000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_11_63',3330000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_11_63',1660000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_12_40',73000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_12_40',36000,' ',0);
Insert into GAME_AWARD (ID,LOTTERYID,BET_TYPE_CODE,ACTUAL_BONUS,AWARD_GROUP_ID,CREATE_TIME,UPDATE_TIME,STATUS,RET_VALUE,BET_TYPE_CODE_PARENT,ACTUAL_BONUS_DOWN,LHC_CODE,LHC_THEORY_BONUS) values (Seq_Game_Award.Nextval,99113,'52_12_41',360000,(select id from GAME_AWARD_GROUP where lotteryid = '99113'),sysdate,sysdate,1,100,'52_12_41',180000,' ',0);


--insert GAME_MULTIPLE
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_10_10',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_10_11',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_10_33',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_10_34',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_11_33',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_11_35',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_11_36',1200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_11_37',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_11_39',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_11_62',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_11_63',1200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_12_40',54570,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'52_12_41',10911,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_10_10',20,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_10_11',20,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_11_49',480,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_11_50',240,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_11_51',120,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_11_52',80,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_12_40',69324,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'51_12_41',19464,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_10_10',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_10_11',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_10_33',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_10_34',200,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_11_33',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_11_35',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_11_36',1201,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_11_37',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_11_39',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_11_62',600,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_11_63',1201,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_12_40',54794,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'47_12_41',11111,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_10_10',2000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_10_11',2000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_10_33',2000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_10_34',2000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_11_10',4000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_11_11',4000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_11_33',4000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'48_11_39',4000,sysdate,sysdate,null);
Insert into GAME_MULTIPLE (ID,LOTTERYID,BET_TYPE_CODE,MAX_MULTIPLE,CREATE_TIME,UPDATE_TIME,SPECIAL_MULTIPLE) values (seq_game_multiple.nextval,99113,'50_14_10',20000,sysdate,sysdate,null);
  


--insert help
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'51_10_10', 
'从千位、百位、十位、个位中选择一个4位数号码组成一注，所选号码与开奖号码相同，且顺序一致，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*3456</br>开奖：*3456</br>奖金："bonus"元', sysdate, sysdate);
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'51_11_49', 
'从0-9中任意选择4个号码组成一注，所选号码与开奖号码的千位、百位、十位、个位相同，且顺序不限，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*2568</br>开奖：*2568（不限顺序）</br>奖金："bonus"元', sysdate, sysdate);
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'51_11_50', 
'选择1个二重号码和2个单号号码组成一注，所选单号号码与开奖号码相同，且所选二重号码在开奖号码中出现了2次，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*2588（8为二重号，2·5为单号）</br>开奖：*2588（不限顺序）</br>奖金："bonus"元', sysdate, sysdate);
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'51_11_51', 
'选择2个二重号码组成一注，所选的2个二重号码在开奖号码中分别出现了2次，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*0088（0·8为二重号）</br>开奖：*0088（不限顺序）</br>奖金："bonus"元', sysdate, sysdate);
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'51_11_52', 
'选择1个三重号码和1个单号号码组成一注，所选单号号码与开奖号码相同，且所选三重号码在开奖号码中出现了3次，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*2888（8为三重号，2为单号）</br>开奖：*2888（不限顺序）</br>奖金："bonus"元', sysdate, sysdate);
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'51_12_40', 
'从0-9中至少选择1个号码投注，竞猜开奖号码后四位中包含这个号码，包含即中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：1</br>开奖：*1xxx（不限顺序）</br>奖金："bonus"元', sysdate, sysdate);
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'51_12_41', 
'从0-9中至少选择2个号码投注，竞猜开奖号码后四位中包含这2个号。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：1，2</br>开奖：*12xx（不限顺序）</br>奖金："bonus"元', sysdate, sysdate);
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_10_10', 
'从千位、百位、十位中选择一个3位数号码组成一注，所选号码与开奖号码中3位相同，且顺序一致，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*456*</br>开奖：*456*</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_10_33', 
'所选数值等于开奖号码的千位、百位、十位三个数字相加之和，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：和值1</br>开奖：*001*,*010*,*100*</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_10_34', 
'所选数值等于开奖号码的中3位最大与最小数字相减之差，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：跨度8</br>开奖：(1)中三数字08x（不限顺寻）,x≠9;</br>(2)后三数字19x（不限顺寻），x≠0</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_11_35', 
'从0-9中选择2个数字组成两注，所选号码与开奖号码的千位、百位、十位相同，且顺序不限，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*112*（1为二重号，2为单号）</br>开奖：*112*（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_11_36', 
'从0-9中任意选择3个号码组成一注，所选号码与开奖号码的千位、百位、十位相同，顺序不限，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：*123*</br>开奖：*123*（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_11_33', 
'所选数值等于开奖号码千位、百位、十位三个数字相加之和(不含豹子号)，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus/bonus2元，相同奖金为bonus/bonus2元。', 
'投注：和值6</br>开奖：(1) *015*（不限顺序），奖金："bonus_63"元</br>(2) *033*（不限顺序），奖金："bonus_62"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_11_39', 
'从0-9中任意选择1个包胆号码，开奖号码的千位、百位、十位中任意1位与所选包胆号码相同(不含豹子号)，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus/bonus2元，相同奖金为bonus/bonus2元。', 
'投注：包胆3</br>开奖：(1) *3xx*或者*33x*（不限顺序）,奖金："bonus_62"元</br>(2) *3xy*（不限顺序）,奖金："bonus_63"元</br>注：x≠y≠3', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_11_37', 
'手动输入一个3位数号码组成一注(不含豹子号)，开奖号码的千位、百位、十位符合中三组三或组六均为中奖。如果开奖号码的万位、千位不相同奖金为bonus/bonus2元，相同奖金为bonus/bonus2元。', 
'投注：(001),(123)</br>开奖：(1)*001*（不限顺序），奖金："bonus_62"元，</br>(2)**123（不限顺序），奖金："bonus_63"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_12_40', 
'从0-9中选择1个号码，每注由1个号码组成，只要开奖号码的千位、百位、十位中包含所选号码，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：1</br>开奖：*1xx*（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'52_12_41', 
'从0-9中选择2个号码，每注由2个不同的号码组成，开奖号码的千位、百位、十位中同时包含所选的2个号码，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：1，2</br>开奖：*12x*（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_10_10', 
'从百位、十位、个位中选择一个3位数号码组成一注，所选号码与开奖号码后3位相同，且顺序一致，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：**456</br>开奖：**456</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_10_33', 
'所选数值等于开奖号码的百位、十位、个位三个数字相加之和，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：和值1</br>开奖：12001,12010,12100</br>奖金："bonus"元</br>开奖：11001,11010,11100</br>奖金："bonus2"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_10_34', 
'所选数值等于开奖号码的后3位最大与最小数字相减之差，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：跨度8</br>开奖：(1)后三数字1208x（不限顺序）,x≠9;(2)后三数字1219x（不限顺序），x≠0</br>奖金："bonus"元</br>开奖：(1)后三数字1108x（不限顺序）,x≠9;(2)后三数字1119x（不限顺序），x≠0</br>奖金："bonus2"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_11_35', 
'从0-9中选择2个数字组成两注，所选号码与开奖号码的百位、十位、个位相同，且顺序不限，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：**112（1为二重号，2为单号）</br>开奖：**112（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_11_36', 
'从0-9中任意选择3个号码组成一注，所选号码与开奖号码的百位、十位、个位相同，顺序不限，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：**123</br>开奖：**123（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_11_33', 
'所选数值等于开奖号码百位、十位、个位三个数字相加之和(不含豹子号)，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus/bonus2元，相同奖金为bonus/bonus2元。', 
'投注：和值6</br>开奖：(1) **015（不限顺序），奖金："bonus_63"元</br>(2) **033（不限顺序），奖金："bonus_62"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_11_39', 
'从0-9中任意选择1个包胆号码，开奖号码的百位、十位、个位中任意1位与所选包胆号码相同(不含豹子号)，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus/bonus2元，相同奖金为bonus/bonus2元。', 
'投注：包胆3</br>开奖：(1) **3xx或者**33x（不限顺序）,奖金："bonus_62"元</br>(2) **3xy（不限顺序）,奖金："bonus_63"元</br>注：x≠y≠3', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_11_37', 
'手动输入一个3位数号码组成一注(不含豹子号)，开奖号码的百位、十位、个位符合后三组三或组六均为中奖。如果开奖号码的万位、千位不相同奖金为bonus/bonus2元，相同奖金为bonus/bonus2元。', 
'投注：(001),(123)</br>开奖：(1)**001（不限顺序），奖金："bonus_62"元，</br>(2)**123（不限顺序），奖金："bonus_63"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_12_40', 
'从0-9中选择1个号码，每注由1个号码组成，只要开奖号码的百位、十位、个位中包含所选号码，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：1</br>开奖：**1xx（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_12_41', 
'从0-9中选择2个号码，每注由2个不同的号码组成，开奖号码的百位、十位、个位中同时包含所选的2个号码，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：1，2</br>开奖：**12x（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'48_10_10', 
'从十位、个位中选择一个2位数号码组成一注，所选号码与开奖号码的十位、个位相同，且顺序一致，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：***45</br>开奖：***45</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_10_33', 
'所选数值等于开奖号码的十位、个位二个数字相加之和，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：和值1</br>开奖：***01,***10</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'47_10_34', 
'所选数值等于开奖号码的后2位最大与最小数字相减之差，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：跨度8</br>开奖：***08,***19, ***80, ***91</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'48_11_10', 
'从0-9中选2个号码组成一注，所选号码与开奖号码的十位、个位相同，顺序不限（不含对子号），即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：5,8</br>开奖：***58(不限顺序)</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'48_11_33', 
'所选数值等于开奖号码的十位、个位二个数字相加之和（不含对子号），即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：和值1</br>开奖：***10（不限顺序）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'48_11_39', 
'从0-9中任意选择1个包胆号码，开奖号码的十位、个位中任意1位包含所选的包胆号码相同（不含对子号），即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：包胆8；</br>开奖：***x8（不限顺序，x≠8）</br>奖金："bonus"元', sysdate, sysdate); 
insert into GAME_HELP (ID, LOTTERYID, BET_TYPE_CODE, GAME_PROMPT_DES, GAME_EXAMPLES_DES, CRETEAT_TIME, UPDATE_TIME)values (seq_game_help.nextval, 99113, 
'50_14_10', 
'从万位、千位、百位、十位、个位任意位置上至少选择1个以上号码，所选号码与相同位置上的开奖号码一致，即为中奖。如果开奖号码的万位、千位不相同奖金为bonus元，相同奖金为bonus2元。', 
'投注：1****</br>开奖：1****</br>奖金："bonus"元', sysdate, sysdate); 

                                 
--INSERT INTO GAME_SERIES_CONFIG
Insert into GAME_SERIES_CONFIG (ID,LOTTERYID,BACKOUT_START_FEE,BACKOUT_RATIO,ISSUEWARN_NOT_OPENAWARD,ISSUEWARN_AHEAD_OPENAWARD,ISSUEWARN_DELAY_OPENAWARD,ISSUEWARN_BACKOUT_TIME,ISSUEWARN_EXCEPTION_TIME,CREATE_TIME,UPDATE_TIME,EMAIL,ISSUEWARN_USER_BACKOUT_TIME,HASVIDEO,VIDESTRUC) values (seq_game_series_id.nextval,99113,0,0,null,null,null,900,900,sysdate,sysdate,null,0,null,null);


--审核设置                                                                                                          
Insert into GAME_RISK_CONFIG (ID,ORDERWARN_MAXWINS,ORDERWARN_WINS_RATIO,ORDERWARN_CONTINUOUS_WINS,ORDERWARN_MAXSLIP_WINS,ORDERWARN_SLIP_WINSRATIO,CREATE_TIME,UPDATE_TIME,LOTTERYID) values (seq_game_risk_config_id.nextval,1500000000,300000,null,500000000,500000,sysdate,sysdate,99113);


