
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "rngSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RngSoap {


    /**
     * 
     * @param param
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "ReceiveNumber", action = "http://tempuri.org/ReceiveNumber")
    @WebResult(name = "ReceiveNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ReceiveNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveNumber")
    @ResponseWrapper(localName = "ReceiveNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReceiveNumberResponse")
    public boolean receiveNumber(
        @WebParam(name = "param", targetNamespace = "http://tempuri.org/")
        String param);

    /**
     * 
     * @param param
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GrabRandomNumber", action = "http://tempuri.org/GrabRandomNumber")
    @WebResult(name = "GrabRandomNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GrabRandomNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GrabRandomNumber")
    @ResponseWrapper(localName = "GrabRandomNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GrabRandomNumberResponse")
    public String grabRandomNumber(
        @WebParam(name = "param", targetNamespace = "http://tempuri.org/")
        String param);

    /**
     * 
     * @param time
     * @param preMin
     * @return
     *     returns org.tempuri.RetrieveHistoryNumberResponse.RetrieveHistoryNumberResult
     */
    @WebMethod(operationName = "RetrieveHistoryNumber", action = "http://tempuri.org/RetrieveHistoryNumber")
    @WebResult(name = "RetrieveHistoryNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RetrieveHistoryNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RetrieveHistoryNumber")
    @ResponseWrapper(localName = "RetrieveHistoryNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RetrieveHistoryNumberResponse")
    public org.tempuri.RetrieveHistoryNumberResponse.RetrieveHistoryNumberResult retrieveHistoryNumber(
        @WebParam(name = "time", targetNamespace = "http://tempuri.org/")
        String time,
        @WebParam(name = "pre_min", targetNamespace = "http://tempuri.org/")
        int preMin);

}
