Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1021, 46, 'FUND_WITHDRAW_DRAWTIPS', 2, 1021, 
    '审核提示配置');

Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1022, 46, 'FUND_WITHDRAW_APPEALTIPS', 2, 1022, 
    '申訴提示配置');

Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1023, 46, 'FUND_WITHDRAW_URGENCY', 2, 1023, 
    '紧急提示');    
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1021);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1022);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1023);


Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1024, 1021, 'FUND_WITHDRAW_DRAWTIPS_UPDATE', 3, 1024, 
    '编辑提示');
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1025, 1021, 'FUND_WITHDRAW_DRAWTIPS_ADD', 3, 1025, 
    '增加提示');
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1026, 1021, 'FUND_WITHDRAW_DRAWTIPS_DELETE', 3, 1026, 
    '删除提示');        

INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1024);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1025);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1026);

    
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1028, 1022, 'FUND_WITHDRAW_APPEALTIPS_UPDATE', 3, 1028, 
    '编辑提示');
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1029, 1022, 'FUND_WITHDRAW_APPEALTIPS_ADD', 3, 1029, 
    '增加提示');
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1030, 1022, 'FUND_WITHDRAW_APPEALTIPS_DELETE', 3, 1030, 
    '删除提示');        

Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1032, 1023, 'FUND_WITHDRAW_URGENCY_SAVE', 3, 1032, 
    '保存');      

INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1028);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1029);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1030);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1032);


Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1033, 32, 'FUND_WITHDRAW_APPEAL', 1, 1033, 
    '提现申诉处理');

--全部
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1034, 1033, 'FUND_WITHDRAW_APPEAL_ALL', 2, 1034, 
    '全部');

Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1035, 1034, 'FUND_WITHDRAW_APPEAL_ALL_QUERY', 3, 1035, 
    '查看');

--未處理
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1036, 1033, 'FUND_WITHDRAW_APPEAL_UNCHECK', 2, 1036, 
    '未处理');

Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1037, 1036, 'FUND_WITHDRAW_APPEAL_UNCHECK_CHECK', 3, 1037, 
    '审核');

--审核通过
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1038, 1033, 'FUND_WITHDRAW_APPEAL_PASS', 2, 1038, 
    '审核通过');

Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1039, 1038, 'FUND_WITHDRAW_APPEAL_PASS_QUERY', 3, 1039, 
    '查看');
    
--审核不通过
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1040, 1033, 'FUND_WITHDRAW_APPEAL_UNPASS', 2, 1040, 
    '审核不通过');    

Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1041, 1040, 'FUND_WITHDRAW_APPEAL_UNPASS_QUERY', 3, 1041, 
    '查看');



INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1033);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1034);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1035);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1036);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1037);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1038);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1039);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1040);
INSERT INTO ACL_GROUP_AUTHORIZATION(ID,GID,ACL_ID)VALUES(SEQ_ACL_GROUP_ID.NEXTVAL,66,1041);