DROP TABLE FIREFOG.FUND_WITHDRAW_LOG;

CREATE TABLE   FIREFOG.FUND_WITHDRAW_LOG 
( ID NUMBER      NOT NULL PRIMARY KEY, 
 WITHDRAW_SN    VARCHAR2 (30 BYTE),         
 LOG_MODEL        varchar2(1),
 LOG_CONTENT    NVARCHAR2 (1000),     
 CREATE_TIME    TIMESTAMP(6));
     
COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_LOG.ID IS '流水號';
COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_LOG.WITHDRAW_SN IS '提現單號';
COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_LOG.LOG_CONTENT IS 'log內容';
COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_LOG.CREATE_TIME IS '建立時間';
COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_LOG.LOG_MODEL IS '0:提現:1申訴';
--建立ID SEQUENCE
CREATE SEQUENCE SEQ_FUND_WITHDRAW_log;

--建立提現單號查詢Index
CREATE INDEX FWL_WITHDRAW_SN ON FUND_WITHDRAW_LOG(WITHDRAW_SN);