ALTER TABLE FIREFOG.FUND_WITHDRAW_TIPS
 DROP PRIMARY KEY CASCADE;

DROP TABLE FIREFOG.FUND_WITHDRAW_TIPS CASCADE CONSTRAINTS;

CREATE TABLE FIREFOG.FUND_WITHDRAW_TIPS
( 
  ID            NUMBER ,
  TIPS_GROUPA   VARCHAR2(1 BYTE)               NOT NULL,
  TIPS_GROUPB   VARCHAR2(1 BYTE)               NOT NULL, 
  TIPS_CONTEXT  VARCHAR2(1000 BYTE),
  CREATE_TIME   TIMESTAMP(6)                    NOT NULL,
  CREATE_USER   VARCHAR2(50 BYTE),
  MODIFY_TIME   TIMESTAMP(6)                    NOT NULL,
  MODIFY_USER   VARCHAR2(50 BYTE),
  TIPS_MEMO     NVARCHAR2(1000));

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.TIPS_GROUPA IS '未處理:0,待複審:1';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.TIPS_GROUPB IS '提示小類 0:未通過 ,1:通過 2:待複審';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.TIPS_CONTEXT IS '文字說明';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.CREATE_TIME IS '建立時間';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.CREATE_USER IS '建立UserName';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.MODIFY_TIME IS '修改時間';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.MODIFY_USER IS '修改UserName';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.TIPS_MEMO IS '備註';


ALTER TABLE FIREFOG.FUND_WITHDRAW_TIPS ADD (
  PRIMARY KEY
  (ID));

CREATE SEQUENCE SEQ_FUND_WITHDRAW_TIPS;

alter table fund_withdraw_tips add (TIPS_MODEL VARCHAR2(1));

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_TIPS.TIPS_MODEL IS '充值:0,提現:1,申訴:2';