
  CREATE TABLE "FIREFOG"."FUND_CHARGE_APPEAL" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"VIP_LVL" NUMBER, 
	"APPEAL_SN" VARCHAR2(30 BYTE) NOT NULL ENABLE, 
	"APPEAL_STATUS" NUMBER, 
	"APPEAL_ACCT" VARCHAR2(50 BYTE), 
	"REVIEW_START_TIME" TIMESTAMP (6), 
	"APPEAL_MEMO" VARCHAR2(2000 BYTE), 
	"ARGUE_TIME" TIMESTAMP (6), 
	"ARGUE_ACCT" VARCHAR2(50 BYTE), 
	"CHARGE_SN" VARCHAR2(30 BYTE), 
	"CHARGE_USER_NAME" VARCHAR2(50 BYTE), 
	"CHARGE_AMT" NUMBER, 
	"CHARGE_TIME" TIMESTAMP (6), 
	"CHARGE_MEMO" VARCHAR2(20 BYTE), 
	"DEPOSITE_MODE" NUMBER(1,0), 
	"BANK_ID" VARCHAR2(10 BYTE), 
	"BANK_NAME" VARCHAR2(60 BYTE), 
	"BANK_CARD_NUMBER" VARCHAR2(40 BYTE), 
	"ELECTRONIC_NUMBER" NUMBER(16,0), 
	"UPLOAD_IMAGES" VARCHAR2(500 BYTE), 
	"REVIEW_END_TIME" TIMESTAMP (6), 
	"REVIEW_MEMO" VARCHAR2(50 BYTE), 
	"TENPAY_ACCOUNT" VARCHAR2(50 BYTE), 
	"TENPAY_NAME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "SYS_C0013430" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 1048576 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIREIDX"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;

   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."ID" IS '流水號';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."USER_ID" IS '用戶ID';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."VIP_LVL" IS '是否VIP  0：不是vip  1：vip   未來有等級區分';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."APPEAL_SN" IS '申訴單號';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."APPEAL_STATUS" IS '0:未處理 1:审核通过  2：审核未通过 6:審核待定';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."APPEAL_ACCT" IS '審核人';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."REVIEW_START_TIME" IS '審核開始時間';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."APPEAL_MEMO" IS '備註';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."ARGUE_TIME" IS '申訴時間';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."ARGUE_ACCT" IS '申訴人';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."CHARGE_SN" IS '充值單號';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."CHARGE_USER_NAME" IS '充值用戶名';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."CHARGE_AMT" IS '充值金額 ';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."CHARGE_TIME" IS '充值時間';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."CHARGE_MEMO" IS '充值附言';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."DEPOSITE_MODE" IS '申请渠道';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."BANK_ID" IS '銀行ID';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."BANK_NAME" IS '銀行名稱';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."BANK_CARD_NUMBER" IS '卡片號碼';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."ELECTRONIC_NUMBER" IS '電子表單號碼';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."UPLOAD_IMAGES" IS '上傳圖片Urls';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."REVIEW_END_TIME" IS '審核結束時間';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."REVIEW_MEMO" IS '管理员审核备注';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."TENPAY_ACCOUNT" IS '財付通帳號';
   COMMENT ON COLUMN "FIREFOG"."FUND_CHARGE_APPEAL"."TENPAY_NAME" IS '財付通姓名';


CREATE SEQUENCE SEQ_FUND_CHARGE_APPEAL_ID INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 20;
