CREATE OR REPLACE FORCE VIEW "FIREFOG"."VIEW_FUND_APPEAL_STATUS" 
("USER_ID", "ACCOUNT", "APPEAL_SN", "APPEAL_TYPE", "APPEAL_TIME", "ARGUE_TIME", "CREATOR", "MEMO", "STATUS", "FUND_SN", "FUND_AMT", "FUND_TIME", "FUND_CARD", "FUND_CARD_USER") AS 
  SELECT 
  FWA.USER_ID AS USER_ID,
  UC.ACCOUNT AS ACCOUNT,
  FWA.APPEAL_SN AS APPEAL_SN,
  'WITHDRAW' AS APPEAL_TYPE,
  FWA.APPEAL_TIME AS APPEAL_TIME,
  FWA.ARGUE_TIME AS ARGUE_TIME,
  FWA.ARGUE_ACCT AS CREATOR,
  FWA.APPEAL_TIPS_RESULT AS MEMO,
  FWA.APPEAL_STATUS AS STATUS,
  FWA.WITHDRAW_SN AS FUND_SN,
  FWA.WITHDRAW_AMT AS FUND_AMT,
  FWA.WITHDRAW_TIME AS FUND_TIME,
  FWA.CARD_NUMBER AS FUND_CARD,
  FWA.USER_NAME AS FUND_CARD_USER,
  NULL AS DEPOSITE_MODE,
  NULL AS BANK_NAME,
  NULL AS TENPAY_ACCOUNT,
  NULL AS TENPAY_NAME
FROM FUND_WITHDRAW_APPEAL FWA
LEFT JOIN USER_CUSTOMER UC ON UC.ID = FWA.USER_ID
UNION 
SELECT 
  FCA.USER_ID AS USER_ID,
  FCA.ARGUE_ACCT AS ACCOUNT,
  FCA.APPEAL_SN AS APPEAL_SN,
  'RECHARGE' AS APPEAL_TYPE,
  FCA.REVIEW_END_TIME AS APPEAL_TIME,
  FCA.ARGUE_TIME AS ARGUE_TIME,
  UC.ACCOUNT AS CREATOR,
  FCA.APPEAL_MEMO AS MEMO,
  FCA.APPEAL_STATUS AS STATUS,
  FCA.CHARGE_SN AS FUND_SN,
  FCA.CHARGE_AMT/10000 AS FUND_AMT,
  FCA.CHARGE_TIME AS FUND_TIME,
  FCA.BANK_CARD_NUMBER AS FUND_CARD,
  FCA.CHARGE_USER_NAME AS FUND_CARD_USER,
  FCA.DEPOSITE_MODE AS DEPOSITE_MODE,
  FCA.BANK_NAME AS BANK_NAME,
  FCA.TENPAY_ACCOUNT AS TENPAY_ACCOUNT,
  FCA.TENPAY_NAME AS TENPAY_NAME
FROM FUND_CHARGE_APPEAL FCA
LEFT JOIN USER_CUSTOMER UC ON UC.ID = FCA.USER_ID;