Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1306, 114, 'USER_MANAGE_LIST_LHC', 3, 1306, 
    '六合彩');
    
    INSERT INTO ACL_GROUP_AUTHORIZATION VALUES(SEQ_ACL_GROUP_AUTH_ID.NEXTVAL,'66','1306');
    
Insert into FIREFOG.ACL
   (ID, PID, NAME, TYPE, ORDERS, 
    LABEL)
 Values
   (1307, 1306, 'USER_MANAGE_LIST_LHC_UPDATE', 1, 1306, 
    '修改');
    
     INSERT INTO ACL_GROUP_AUTHORIZATION VALUES(SEQ_ACL_GROUP_AUTH_ID.NEXTVAL,'66','1307');