REM INSERTING into GAME_SERIES
SET DEFINE OFF;
Insert into GAME_SERIES (ID,LOTTERY_TYPE_CODE,LOTTERY_TYPE_NAME,LOTTERY_SERIES_CODE,LOTTERY_SERIES_NAME,LOTTERYID,LOTTERY_NAME,STATUS,CREATE_TIME,UPDATE_TIME,MINI_LOTTERY_PROFIT,LOTTERY_HELP_DES,MAX_COUNT_ISSUE,LOTTERY_IS_LOCK,CHANGE_STATUS,EMAIL,VIEW_ORDER,OPERATE_ORDER,TAKEOFF_TIME) values (SEQ_GAME_SERIES.Nextval,1,'乐透同区型',2,'六合系',99701,'六合彩',1,to_timestamp('2014-06-13 16:55:05','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2016-04-27 16:19:13','YYYY-MM-DD HH24:MI:SS'),0.04,null,20,255,11111111,null,null,null,null);
