ALTER TABLE GAME_AWARD_GROUP ADD LHC_YEAR NUMBER;
ALTER TABLE GAME_AWARD_GROUP ADD LHC_COLOR NUMBER;
COMMENT ON COLUMN "GAME_AWARD_GROUP"."LHC_YEAR" IS '六合彩生肖返點';
COMMENT ON COLUMN "GAME_AWARD_GROUP"."LHC_COLOR" IS '六合彩兩面色波返點';


Insert into GAME_AWARD_GROUP (ID,LOTTERYID,AWARD_NAME,DIRECT_RET,THREEONE_RET,STATUS,SYS_AWARD_GROUP,CREATE_TIME,UPDATE_TIME,PARAMS,AWARD_RET_STATUS,SUPER_RET,SUPER_PAIR_STATUS,LHC_YEAR,LHC_COLOR) values (SEQ_GAME_AWARD_GROUP.Nextval,99701,'六合彩奖金组',1400,0,1,1,to_timestamp('2016-04-21 02:48:32','YYYY-MM-DD HH24:MI:SS'),to_timestamp('2016-04-21 02:48:35','YYYY-MM-DD HH24:MI:SS'),null,1,0,0,500,200);
