ALTER TABLE GAME_AWARD_USER_GROUP ADD LHC_YEAR NUMBER;
ALTER TABLE GAME_AWARD_USER_GROUP ADD LHC_COLOR NUMBER;
COMMENT ON COLUMN "GAME_AWARD_USER_GROUP"."LHC_YEAR" IS '六合彩生肖返點';
COMMENT ON COLUMN "GAME_AWARD_USER_GROUP"."LHC_COLOR" IS '六合彩兩面色波返點';


