--------------------------------------------------------
--  File created - Thursday-December-26-2013   
--------------------------------------------------------
DROP TABLE "FIREFOG"."AD_PARAM" cascade constraints;
DROP TABLE "FIREFOG"."AD_PAGE" cascade constraints;
DROP TABLE "FIREFOG"."AD_SPACE" cascade constraints;
--------------------------------------------------------
--  DDL for Table AD_PARAM
--------------------------------------------------------

  CREATE TABLE "FIREFOG"."AD_PARAM" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"POSITION" VARCHAR2(30 BYTE), 
	"WIDTH" NUMBER, 
	"HEIGHT" NUMBER, 
	"PAGE_MEMO" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
 

   COMMENT ON COLUMN "FIREFOG"."AD_PARAM"."POSITION" IS '位置描述';
 
   COMMENT ON COLUMN "FIREFOG"."AD_PARAM"."WIDTH" IS '宽度 -1 表示无限制';
 
   COMMENT ON COLUMN "FIREFOG"."AD_PARAM"."HEIGHT" IS '长度 -1表示无限制';
--------------------------------------------------------
--  DDL for Table AD_PAGE
--------------------------------------------------------

  CREATE TABLE "FIREFOG"."AD_PAGE" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"MEMO" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
 

   COMMENT ON COLUMN "FIREFOG"."AD_PAGE"."NAME" IS '名字';
 
   COMMENT ON COLUMN "FIREFOG"."AD_PAGE"."MEMO" IS '描述';
--------------------------------------------------------
--  DDL for Table AD_SPACE
--------------------------------------------------------

  CREATE TABLE "FIREFOG"."AD_SPACE" 
   (	"ID" NUMBER, 
	"AD_PARAM_ID" NUMBER, 
	"WIDTH" NUMBER, 
	"HEIGHT" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"URL_TARGET" NUMBER, 
	"DFT_IMG" VARCHAR2(100 BYTE), 
	"IS_USED" NUMBER, 
	"PAGE_ID" NUMBER, 
	"DFT_IMGS" VARCHAR2(1000 BYTE), 
	"IS_DFT_USED" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
 

   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."AD_PARAM_ID" IS '广告位参数id';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."WIDTH" IS '宽度';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."HEIGHT" IS '高度';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."NAME" IS '位置名称';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."URL_TARGET" IS 'url打开参数  1）新窗口 2）老窗口';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."DFT_IMG" IS '当前占位图';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."IS_USED" IS '1)启用  0）不可用';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."PAGE_ID" IS '页面id';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."DFT_IMGS" IS '所有占位图';
 
   COMMENT ON COLUMN "FIREFOG"."AD_SPACE"."IS_DFT_USED" IS '1开启  0未开启';

Insert into FIREFOG.AD_PARAM (ID,NAME,POSITION,WIDTH,HEIGHT,PAGE_MEMO) values (1,'left_ad','左侧广告
',1024,768,'ssss');
Insert into FIREFOG.AD_PARAM (ID,NAME,POSITION,WIDTH,HEIGHT,PAGE_MEMO) values (2,'foot_ad','下侧广告
',1024,768,'eeee');

Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (1,'ad_index','平台首页');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (2,'ad_top','平台顶部');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (3,'ad_foot','平台底部');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (4,'ad_reg','注册页');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (5,'ad_login','登录页');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (6,'ad_cqssc','重庆时时彩');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (7,'ad_jxssc','江西时时彩');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (8,'ad_xjssc','新疆时时彩');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (9,'ad_tjssc','天津时时彩');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (10,'ad_hljssc','黑龙江时时彩');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (11,'ad_shssc','上海时时彩');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (12,'ad_llssc','乐利时时彩');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (13,'ad_sd115','山东11选5');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (14,'ad_jx115','江西11选5');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (15,'ad_gd115','广东11选5');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (16,'ad_cq115','重庆11选5');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (17,'ad_ll115','乐利11选5');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (18,'ad_bjkl8','北京快乐8');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (19,'ad_3d','3D');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (20,'ad_p5','排列5');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (21,'ad_ssq','双球');
Insert into FIREFOG.AD_PAGE (ID,NAME,MEMO) values (23,'ad_pt','PT');

Insert into FIREFOG.AD_SPACE (ID,AD_PARAM_ID,WIDTH,HEIGHT,NAME,URL_TARGET,DFT_IMG,IS_USED,PAGE_ID,DFT_IMGS,IS_DFT_USED) values (1,1,230,250,'index_pos_left_1',1,null,1,1,null,1);
Insert into FIREFOG.AD_SPACE (ID,AD_PARAM_ID,WIDTH,HEIGHT,NAME,URL_TARGET,DFT_IMG,IS_USED,PAGE_ID,DFT_IMGS,IS_DFT_USED) values (2,1,230,75,'index_pos_left_2',1,null,1,1,null,1);
Insert into FIREFOG.AD_SPACE (ID,AD_PARAM_ID,WIDTH,HEIGHT,NAME,URL_TARGET,DFT_IMG,IS_USED,PAGE_ID,DFT_IMGS,IS_DFT_USED) values (3,1,320,120,'index_pos_loginTop',1,null,1,5,null,1);
Insert into FIREFOG.AD_SPACE (ID,AD_PARAM_ID,WIDTH,HEIGHT,NAME,URL_TARGET,DFT_IMG,IS_USED,PAGE_ID,DFT_IMGS,IS_DFT_USED) values (4,1,400,300,'index_pos_loginCenter',1,null,1,4,null,1);
--------------------------------------------------------
--  DDL for Index SYS_C0020087
--------------------------------------------------------

  CREATE UNIQUE INDEX "FIREFOG"."SYS_C0020087" ON "FIREFOG"."AD_PARAM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020085
--------------------------------------------------------

  CREATE UNIQUE INDEX "FIREFOG"."SYS_C0020085" ON "FIREFOG"."AD_PAGE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
--------------------------------------------------------
--  DDL for Index SYS_C0020088
--------------------------------------------------------

  CREATE UNIQUE INDEX "FIREFOG"."SYS_C0020088" ON "FIREFOG"."AD_SPACE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
--------------------------------------------------------
--  Constraints for Table AD_PARAM
--------------------------------------------------------

  ALTER TABLE "FIREFOG"."AD_PARAM" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "FIREFOG"."AD_PARAM" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AD_PAGE
--------------------------------------------------------

  ALTER TABLE "FIREFOG"."AD_PAGE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "FIREFOG"."AD_PAGE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AD_SPACE
--------------------------------------------------------

  ALTER TABLE "FIREFOG"."AD_SPACE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "FIREFOG"."AD_SPACE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE"  ENABLE;
