ALTER TABLE FIREFOG.FUND_WITHDRAW_URGENCY
 DROP PRIMARY KEY CASCADE;

DROP TABLE FIREFOG.FUND_WITHDRAW_URGENCY CASCADE CONSTRAINTS;

CREATE TABLE FIREFOG.FUND_WITHDRAW_URGENCY
(
  ID               NUMBER              NOT NULL,
  URGENCY_CONTEXT  NVARCHAR2(2000),
  CREATE_TIME   TIMESTAMP(6)                    NOT NULL,
  CREATE_USER   VARCHAR2(50));

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_URGENCY.URGENCY_CONTEXT IS '緊急提示文字說明';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_URGENCY.CREATE_TIME IS '建立時間';

COMMENT ON COLUMN FIREFOG.FUND_WITHDRAW_URGENCY.CREATE_USER IS '建立UserName';

ALTER TABLE FIREFOG.FUND_WITHDRAW_URGENCY ADD (
  PRIMARY KEY
  (ID));

CREATE SEQUENCE SEQ_FUND_WITHDRAW_URGENCY;