CREATE TABLE "NOTICE_MSG_PUSH" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"USER_ID" NUMBER NOT NULL ENABLE, 
	"NOTICE_MSG_ID" NUMBER NOT NULL ENABLE,
	"IS_READ" NUMBER(1)DEFAULT 0 NOT NULL ENABLE , 
	"CREATE_DATE" DATE NOT NULL ENABLE, 
	"UPDATE_DATE" DATE, 
	 CONSTRAINT "NOTICE_MSG_PUSH_PK" PRIMARY KEY ("ID"));

   COMMENT ON COLUMN "NOTICE_MSG_PUSH"."ID" IS '流水号';
   COMMENT ON COLUMN "NOTICE_MSG_PUSH"."USER_ID" IS '收ID';
   COMMENT ON COLUMN "NOTICE_MSG_PUSH"."NOTICE_MSG_ID" IS '系统通知讯息ID';
   COMMENT ON COLUMN "NOTICE_MSG_PUSH"."IS_READ" IS '是否读取 0:否 1:是';
   COMMENT ON COLUMN "NOTICE_MSG_PUSH"."CREATE_DATE" IS '建立时间';
   COMMENT ON COLUMN "NOTICE_MSG_PUSH"."UPDATE_DATE" IS '更新时间';

  CREATE INDEX "IDX_NOTICE_MSG_PUSH_UID" ON "NOTICE_MSG_PUSH" ("USER_ID", "CREATE_DATE") ;

  CREATE INDEX "IDX_NOTICE_MSG_PUSH_NID" ON "NOTICE_MSG_PUSH" ("NOTICE_MSG_ID", "CREATE_DATE") ;

  CREATE INDEX "IDX_NOTICE_MSG_PUSH_ID01" ON "NOTICE_MSG_PUSH" ("USER_ID", "ID") ;
  
     CREATE SEQUENCE "SEQ_NOTICE_MSG_PUSH_ID"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1;