CREATE TABLE ACTIVITY_DOUBLEBOX_LOG(
ID  NUMBER(20,0) PRIMARY KEY,
USER_ID	NUMBER(20,0),
USER_ACCOUNT VARCHAR2(70 BYTE),
ACTIVITY_ID	NUMBER(20,0),
CREATE_TIME TIMESTAMP(6),
MULTIPLE NUMBER,
MULTIPLE_PRIZE NUMBER,
SALES NUMBER
);

COMMENT ON COLUMN FIREFOG.ACTIVITY_DOUBLEBOX_LOG.CREATE_TIME IS '建立時間';
COMMENT ON COLUMN FIREFOG.ACTIVITY_DOUBLEBOX_LOG.MULTIPLE IS '翻倍倍數';
COMMENT ON COLUMN FIREFOG.ACTIVITY_DOUBLEBOX_LOG.MULTIPLE_PRIZE IS '翻倍(總)獎金';
COMMENT ON COLUMN FIREFOG.ACTIVITY_DOUBLEBOX_LOG.SALES IS '銷量(投注量)';


CREATE SEQUENCE  SEQ_ACTIVITY_DOUBLEBOX_LOG;

CREATE INDEX ACTIVITY_DOUBLEBOX_LOG_USERID ON  ACTIVITY_DOUBLEBOX_LOG(USER_ID);

INSERT INTO ACTIVITY_CONFIG VALUES(
  6,to_date('2016-05-23 00:00:00','yyyy-mm-dd hh24:mi:ss'),to_date('2016-05-29 :00:00','yyyy-mm-dd hh24:mi:ss'),0,0,''
);