alter session set nls_date_language='american';
Set define OFF;
--------------------------------------------------------
--  File created - Friday-December-27-2013   
--------------------------------------------------------
DROP TABLE "FIREFOG"."USER_URL" cascade constraints;
--------------------------------------------------------
--  DDL for Table USER_URL
--------------------------------------------------------

  CREATE TABLE "FIREFOG"."USER_URL" 
   (	"ID" NUMBER, 
	"CREATOR" NUMBER, 
	"GMT_CREATED" TIMESTAMP (6), 
	"URL" VARCHAR2(100 BYTE), 
	"MEMO" VARCHAR2(24 BYTE), 
	"TYPE" NUMBER, 
	"USERAWARD_LIST_STRUC" VARCHAR2(2000 BYTE), 
	"REGISTERS" NUMBER DEFAULT 0, 
	"USERAWARD" NUMBER, 
	"UUID" VARCHAR2(36 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
 

   COMMENT ON COLUMN "FIREFOG"."USER_URL"."MEMO" IS '备注';
 
   COMMENT ON COLUMN "FIREFOG"."USER_URL"."TYPE" IS '1 代理  0 普通用户';
 
   COMMENT ON COLUMN "FIREFOG"."USER_URL"."USERAWARD_LIST_STRUC" IS '奖金组列表基本结构';
 
   COMMENT ON COLUMN "FIREFOG"."USER_URL"."REGISTERS" IS '已注册用户 0为未注册 其他为已注册';
 
   COMMENT ON COLUMN "FIREFOG"."USER_URL"."USERAWARD" IS '保留饭店 *10';
--------------------------------------------------------
--  DDL for Index USER_PRIMARY_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "FIREFOG"."USER_PRIMARY_ID" ON "FIREFOG"."USER_URL" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE" ;
--------------------------------------------------------
--  Constraints for Table USER_URL
--------------------------------------------------------

  ALTER TABLE "FIREFOG"."USER_URL" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "FIREFOG"."USER_URL" ADD CONSTRAINT "USER_PRIMARY_ID" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FIRE"  ENABLE;
