DROP TABLE FIREFOG.ACTIVITY_VIP_APPLICATION CASCADE CONSTRAINTS;

CREATE TABLE FIREFOG.ACTIVITY_VIP_APPLICATION
(
  ID       NUMBER   PRIMARY KEY,
  ACCOUNT  VARCHAR2(24 BYTE)                    NOT NULL,
  MONTH    NUMBER                               NOT NULL,
  SOURCE    NUMBER                               NOT NULL
 
)
TABLESPACE FIRE
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            MAXSIZE          UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;

COMMENT ON COLUMN FIREFOG.ACTIVITY_VIP_APPLICATION.ACCOUNT IS '報名帳號';
COMMENT ON COLUMN FIREFOG.ACTIVITY_VIP_APPLICATION.MONTH IS '報名月份';
COMMENT ON COLUMN FIREFOG.ACTIVITY_VIP_APPLICATION.SOURCE IS '來源';

CREATE SEQUENCE  SEQ_VIP_AVTIVITY;