
ALTER TABLE FUND_BANK ADD ('HELP_ID' VARCHAR2(20));
COMMENT ON COLUMN FUND_BANK.HELP_ID IS '帮助中心ID 0:无,网银/快捷';

ALTER TABLE FUND_BANK ADD (IS_APPEAL NUMBER default 0);
COMMENT ON COLUMN FUND_BANK.IS_APPEAL IS '是否可申訴 0:否 1:是';

ALTER TABLE FUND_BANK ADD (CAN_RECHARGE_APPEAL NUMBER default 0);
COMMENT ON COLUMN FUND_BANK.CAN_RECHARGE_APPEAL IS '是否可申訴 0:否 1:是';

ALTER TABLE FUND_BANK ADD (OTHER_CAN_RECHARGE_APPEAL NUMBER default 0);
COMMENT ON COLUMN FUND_BANK.OTHER_CAN_RECHARGE_APPEAL IS '第三方是否可申訴 0:否 1:是';


















